# Generated by Django 6.0.5 on 2026-09-21 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_loyalty_promos'),
        ('sales', '0001_initial'),
        ('syncing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyentry',
            name='sync_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='syncing.cloudsyncevent'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyentry',
            constraint=models.UniqueConstraint(fields=('sync_event', 'kind'), name='one_loyalty_entry_per_event_kind'),
        ),
    ]
