# Generated by Django 6.0.5 on 2026-05-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='biometric_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='biometric_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pin_code',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
