# Generated by Django 6.0.5 on 2026-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Xantara POS', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('currency_symbol', models.CharField(default='₱', max_length=5)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=50)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('vat_inclusive', models.BooleanField(default=False)),
                ('show_vat_receipt', models.BooleanField(default=True)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('print_auto', models.BooleanField(default=True)),
                ('email_receipt', models.BooleanField(default=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('pay_cash', models.BooleanField(default=True)),
                ('pay_card', models.BooleanField(default=True)),
                ('pay_gcash', models.BooleanField(default=True)),
                ('pay_maya', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
            },
        ),
    ]
