# Generated by Django 6.0.5 on 2026-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_add_is_active_to_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_code',
            field=models.CharField(db_index=True, default='0000', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
    ]
