# Generated by Django 6.0.5 on 2026-09-29 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def ensure_transactional_registration(apps, schema_editor):
    # Registration relies on row locks and rollback. Some legacy local installs
    # use MyISAM; retain their data while making only these dependencies transactional.
    if schema_editor.connection.vendor != 'mysql':
        return
    schema_editor.execute('SET SESSION default_storage_engine=INNODB')
    for app, name in [('accounts', 'Staff'), ('inventory', 'Branch'),
                      ('syncing', 'SyncInstallation'), ('settings_app', 'StoreSettings')]:
        table = apps.get_model(app, name)._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s', [table])
            engine = cursor.fetchone()[0]
        if engine.upper() != 'INNODB':
            schema_editor.execute(f'ALTER TABLE {schema_editor.quote_name(table)} ENGINE=InnoDB')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventorybatch_receiving_pricing'),
        ('settings_app', '0007_store_setup_state'),
        ('syncing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(ensure_transactional_registration, migrations.RunPython.noop, atomic=False),
        migrations.CreateModel(
            name='FiscalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=200)),
                ('tin', models.CharField(max_length=9)),
                ('address', models.TextField()),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('nonVat', 'Non-VAT')], max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=5, unique=True)),
                ('rdo', models.CharField(max_length=3)),
                ('registered_address', models.TextField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.branch')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terminal_code', models.CharField(max_length=16, unique=True)),
                ('machine_serial', models.CharField(max_length=100, unique=True)),
                ('min', models.CharField(max_length=100, unique=True)),
                ('ptu', models.CharField(max_length=100)),
                ('ptu_issued_on', models.DateField()),
                ('starting_serial', models.PositiveIntegerField(default=1)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_hash', models.CharField(blank=True, max_length=128)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.fiscalbranch')),
                ('installation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='syncing.syncinstallation')),
            ],
        ),
    ]
