# Generated by Django 6.0.5 on 2026-08-21 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_alter_product_barcodetype_alter_product_buyerid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(db_index=True, max_length=64)),
                ('installation_id', models.CharField(max_length=64, unique=True)),
                ('terminal_id', models.CharField(max_length=64)),
                ('local_branch_id', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_installations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_installations', to='inventory.branch')),
            ],
            options={
                'db_table': 'sync_installation',
                'ordering': ['business_id', 'installation_id'],
            },
        ),
        migrations.CreateModel(
            name='CloudSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(db_index=True, max_length=64)),
                ('local_branch_id', models.CharField(max_length=64)),
                ('local_event_id', models.CharField(max_length=64)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=96)),
                ('idempotency_key', models.CharField(max_length=191)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField()),
                ('device_created_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_events', to='inventory.branch')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='syncing.syncinstallation')),
            ],
            options={
                'db_table': 'cloud_sync_event',
                'ordering': ['accepted_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='syncinstallation',
            constraint=models.UniqueConstraint(fields=('business_id', 'terminal_id'), name='uniq_sync_business_terminal'),
        ),
        migrations.AddConstraint(
            model_name='syncinstallation',
            constraint=models.UniqueConstraint(fields=('business_id', 'local_branch_id', 'installation_id'), name='uniq_sync_business_branch_install'),
        ),
        migrations.AddIndex(
            model_name='cloudsyncevent',
            index=models.Index(fields=['business_id', 'local_branch_id', 'accepted_at'], name='idx_sync_business_branch_time'),
        ),
        migrations.AddConstraint(
            model_name='cloudsyncevent',
            constraint=models.UniqueConstraint(fields=('business_id', 'idempotency_key'), name='uniq_sync_business_idempotency'),
        ),
    ]
