# Generated by Django 6.0.5 on 2026-09-12 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.PositiveIntegerField(db_index=True)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=10)),
                ('unit_bldg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Philippines', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['supplier_id', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.PositiveIntegerField(db_index=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['supplier_id', '-is_default'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.PositiveIntegerField(db_index=True)),
                ('contact_name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['supplier_id', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.PositiveIntegerField(db_index=True)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['supplier_id', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('trade_name', models.CharField(blank=True, max_length=150, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=150, null=True)),
                ('tin', models.CharField(blank=True, max_length=30, null=True)),
                ('business_permit_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_vat_registered', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(default='COD', max_length=20)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=0)),
                ('supplier_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('local', 'Local'), ('imported', 'Imported')], default='local', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accredited', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
