# Generated by Django 6.0.5 on 2026-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_purchaseorder_purchaseorderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieraddress',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplierbankdetail',
            name='account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='supplierbankdetail',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierbankdetail',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='supplierproductcategory',
            name='category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
