# Generated by Django 6.0.5 on 2026-06-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'db_table': 'branch',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='beg_balance_sa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='beg_balance_sr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='beg_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_book_sa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_book_sr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_limit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_onorder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_reserved',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_rop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_sa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_sr',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(db_index=True, max_length=15)),
                ('branch_code', models.CharField(db_index=True, max_length=10)),
                ('stock_sa', models.FloatField(default=0.0)),
                ('stock_book_sa', models.FloatField(default=0.0)),
                ('beg_balance_sa', models.FloatField(default=0.0)),
                ('stock_sr', models.FloatField(default=0.0)),
                ('stock_book_sr', models.FloatField(default=0.0)),
                ('beg_balance_sr', models.FloatField(default=0.0)),
                ('stock_reserved', models.FloatField(default=0.0)),
                ('stock_rop', models.FloatField(default=0.0)),
                ('stock_limit', models.FloatField(default=0.0)),
                ('stock_onorder', models.FloatField(default=0.0)),
                ('beg_cost', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_stock',
                'indexes': [models.Index(fields=['branch_code', 'itemcode'], name='idx_stock_branch_item')],
                'unique_together': {('itemcode', 'branch_code')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(db_index=True, max_length=15)),
                ('branch_code', models.CharField(db_index=True, max_length=10)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Customer return'), ('void', 'Void / cancel'), ('receive', 'Stock receiving'), ('adjustment', 'Manual adjustment'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('write_off', 'Write-off / damage')], db_index=True, max_length=20)),
                ('location', models.CharField(choices=[('sa', 'Sales area'), ('sr', 'Store room')], default='sa', max_length=2)),
                ('qty', models.FloatField()),
                ('qty_before', models.FloatField()),
                ('qty_after', models.FloatField()),
                ('ref_no', models.CharField(blank=True, db_index=True, max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'stock_movement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['itemcode', 'branch_code', 'created_at'], name='idx_movement_item_branch_date'), models.Index(fields=['movement_type', 'created_at'], name='idx_movement_type_date'), models.Index(fields=['ref_no'], name='idx_movement_ref')],
            },
        ),
    ]
