# Generated by Django 6.0.5 on 2026-07-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_branch_remove_product_beg_balance_sa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beg_balance_sa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='beg_balance_sr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='beg_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_book_sa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_book_sr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_onorder',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_reserved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_rop',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_sa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_sr',
            field=models.FloatField(default=0.0),
        ),
    ]
