# Generated by Django 6.0.5 on 2026-09-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_barcodetype_alter_product_buyerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='basic', max_length=12)),
                ('data', models.JSONField(default=dict)),
                ('branch_data', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_profile', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_profile',
            },
        ),
        migrations.CreateModel(
            name='InventoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=10)),
                ('revision', models.PositiveIntegerField()),
                ('actor', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_revisions', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_revision',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('product', 'revision'), name='unique_inventory_revision')],
            },
        ),
    ]
