# Generated by Django 6.0.5 on 2026-09-09 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_central_opening_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost_centavos', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBatchBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('sa', 'Sales area'), ('sr', 'Store room')], default='sa', max_length=2)),
                ('quantity', models.FloatField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.inventorybatch')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_balances', to='inventory.productstock')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBatchMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=10)),
                ('kind', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('quantity_before', models.FloatField()),
                ('quantity_after', models.FloatField()),
                ('reason', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventorybatch')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('product', 'number'), name='unique_product_batch'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchbalance',
            constraint=models.UniqueConstraint(fields=('batch', 'stock', 'location'), name='unique_batch_stock_location'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='batch_quantity_nonnegative'),
        ),
    ]
