# Generated by Django 6.0.5 on 2026-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_preserve_existing_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='supplier_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
