# Generated by Django 6.0.5 on 2026-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorybatch_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryprofile',
            name='last_purchase_supplier_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
